import { FileText, Download, BarChart2, PieChart, TrendingUp } from 'lucide-react';
import SuperAdminSidebar from '../../components/SuperAdminSidebar';

export default function Reports() {
  return (
    <div className="min-h-screen bg-[#f8f9fa] flex">
      <SuperAdminSidebar />
      
      <main className="flex-1 p-8 lg:p-12 overflow-y-auto">
        <header className="mb-12">
          <h1 className="text-4xl font-black text-slate-900 tracking-tight uppercase mb-2">Reports & Analytics</h1>
          <p className="text-slate-500 font-medium">Generate and view detailed reports on company metrics.</p>
        </header>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-12">
          {[
            { label: 'Attendance Report', icon: BarChart2, color: 'bg-blue-500' },
            { label: 'Payroll Summary', icon: PieChart, color: 'bg-emerald-500' },
            { label: 'Performance Metrics', icon: TrendingUp, color: 'bg-indigo-500' },
          ].map((report, index) => (
            <div key={index} className="bg-white p-6 rounded-[2rem] shadow-xl border border-slate-100 flex flex-col items-center justify-center text-center gap-4 hover:border-blue-100 hover:bg-blue-50/50 transition-colors cursor-pointer group">
              <div className={`w-16 h-16 rounded-2xl flex items-center justify-center text-white shadow-lg ${report.color} group-hover:scale-110 transition-transform`}>
                <report.icon size={28} />
              </div>
              <p className="text-sm font-black text-slate-900 uppercase tracking-wider">{report.label}</p>
              <button className="flex items-center gap-2 px-4 py-2 bg-slate-100 text-slate-600 rounded-xl text-xs font-bold hover:bg-slate-200 transition-colors">
                <Download size={14} /> Generate
              </button>
            </div>
          ))}
        </div>

        <div className="bg-white p-8 rounded-[2.5rem] shadow-xl border border-slate-100">
          <div className="flex items-center justify-between mb-8">
            <h2 className="text-lg font-black text-slate-900 uppercase tracking-wider">Recent Reports Generated</h2>
          </div>
          <div className="space-y-4">
            {[1, 2, 3].map((i) => (
              <div key={i} className="flex items-center justify-between p-4 rounded-2xl border border-slate-100">
                <div className="flex items-center gap-4">
                  <div className="w-10 h-10 rounded-full bg-slate-100 flex items-center justify-center text-slate-500 shrink-0">
                    <FileText size={20} />
                  </div>
                  <div>
                    <p className="text-sm font-bold text-slate-900">Q3 Financial Summary</p>
                    <p className="text-xs text-slate-500 mt-1">Generated by Admin • 2 hours ago</p>
                  </div>
                </div>
                <button className="p-2 text-blue-600 hover:bg-blue-50 rounded-lg transition-colors">
                  <Download size={18} />
                </button>
              </div>
            ))}
          </div>
        </div>
      </main>
    </div>
  );
}
