import { 
  LayoutDashboard, 
  Clock, 
  Network, 
  CalendarCheck, 
  Award, 
  Building2, 
  Users, 
  UserPlus, 
  UserCheck, 
  UserMinus, 
  CalendarOff, 
  Bell, 
  DollarSign, 
  Target, 
  Laptop, 
  ClipboardList, 
  Megaphone, 
  FileText, 
  CircleDot, 
  MessageSquare, 
  Package, 
  Briefcase, 
  Receipt, 
  UsersRound, 
  ShoppingBag, 
  Settings
} from 'lucide-react';

export const employerModules = [
  { name: 'DASHBOARD', icon: LayoutDashboard, path: '/super-admin/employer/dashboard' },
  { name: 'TIME TRACK', icon: Clock, path: '/super-admin/employer/time-track' },
  { name: 'ORG CHART', icon: Network, path: '/super-admin/employer/org-chart', hasDropdown: true },
  { name: 'ATTENDANCE', icon: CalendarCheck, path: '/super-admin/employer/attendance' },
  { name: 'AWARD', icon: Award, path: '/super-admin/employer/award' },
  { name: 'DEPARTMENT', icon: Building2, path: '/super-admin/employer/department' },
  { name: 'DESIGNATION', icon: Users, path: '/super-admin/employer/designation' },
  { name: 'EMPLOYEE', icon: Users, path: '/super-admin/employer/employee' },
  { name: 'RECRUITMENT', icon: UserPlus, path: '/super-admin/employer/recruitment', hasDropdown: true },
  { name: 'ONBOARDING', icon: UserCheck, path: '/super-admin/employer/onboarding', hasDropdown: true },
  { name: 'OFFBOARDING', icon: UserMinus, path: '/super-admin/employer/offboarding', hasDropdown: true },
  { name: 'LEAVES', icon: CalendarOff, path: '/super-admin/employer/leaves' },
  { name: 'NOTICE BOARD', icon: Bell, path: '/super-admin/employer/notice-board' },
  { name: 'PAYROLL', icon: DollarSign, path: '/super-admin/employer/payroll', hasDropdown: true },
  { name: 'PERFORMANCE', icon: Target, path: '/super-admin/employer/performance', hasDropdown: true },
  { name: 'ASSETS', icon: Laptop, path: '/super-admin/employer/assets' },
  { name: 'PROJECT MANAGEMENT', icon: ClipboardList, path: '/super-admin/employer/projects', hasDropdown: true },
  { name: 'MARKETING', icon: Megaphone, path: '/super-admin/employer/marketing', hasDropdown: true },
  { name: 'REPORTS', icon: FileText, path: '/super-admin/employer/reports' },
  { name: 'REWARD POINTS', icon: CircleDot, path: '/super-admin/employer/rewards' },
  { name: 'MESSAGE', icon: MessageSquare, path: '/super-admin/employer/message' },
  { name: 'SUPPLY CHAIN MANAGEMENT', icon: Package, path: '/super-admin/employer/supply-chain' },
  { name: 'PROCUREMENT', icon: Briefcase, path: '/super-admin/employer/procurement', hasDropdown: true },
  { name: 'ACCOUNTING', icon: Receipt, path: '/super-admin/employer/accounting' },
  { name: 'CRM', icon: UsersRound, path: '/super-admin/employer/crm', hasDropdown: true },
  { name: 'PURCHASE DEP', icon: ShoppingBag, path: '/super-admin/employer/purchase' },
  { name: 'SETTINGS', icon: Settings, path: '/super-admin/employer/settings', hasDropdown: true },
];
